projeto/forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'
urlpatterns = [
    # index
    path("", views.index, name="index"),
    # detalhe
    path('<int:post_id>', views.detalhe, name='detalhe'),
    # criar post
    path("criarpost", views.criarpost, name='criarpost'),
    # remover post
    path('<int:post_id>/removerpost', views.removerpost, name='removerpost'),
    # remover comentario
    path('<int:comentario_id>/removercomentario', views.removercomentario, name='removercomentario'),
    # gosto post
    path('<int:post_id>/gosto_post', views.gosto_post, name='gosto_post'),
    # login
    path("login", views.fazerLogin, name='fazerLogin'),
    # signin
    path('signin', views.signIn, name='signin'),
    # logout
    path('logout', views.fazerLogout, name='logout'),
    # info
    path('info', views.info, name='info'),
    # comentario
    path('<int:post_id>/criarcomentario', views.criarcomentario, name='criarcomentario'),
    # gosto comentario
    path('<int:comentario_id>/gosto_comentario', views.gosto_comentario, name='gosto_comentario'),
    # upload de imagens
    path('fazer_upload', views.fazer_upload, name='fazer_upload'),
    # upload de imagens avatar
    path('fazer_upload_avatar', views.fazer_upload_avatar, name='fazer_upload_avatar'),
    # subcomentario
    path('<int:comentario_id>/criarsubcomentario', views.criarsubcomentario, name='criarsubcomentario'),
    # index noticias
    path('index_noticia', views.index_noticia, name='index_noticia'),
    # criar noticia
    path("criarnoticia", views.criarnoticia, name='criarnoticia'),
]

projeto/projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('forum/', include('forum.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto/forum/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.functions import datetime
from django.utils import timezone


class Condutor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    modelo_carro = models.CharField(max_length=50)
    numero_posts = models.IntegerField(default=0)
    avatar = models.ImageField(default='forum/images/default.png', blank=True)


class Post(models.Model):
    post_titulo = models.CharField(max_length=50)
    post_texto = models.CharField(max_length=500)
    pub_data = models.DateTimeField('data de publicacao')
    gostos = models.IntegerField(default=0)
    imagem = models.ImageField(blank=True)

    def __str__(self):
        return self.imagem

    def __str__(self):
        return self.post_titulo

    def __str__(self):
        return self.post_texto

    def foi_publicado_recentemente(self):
        return self.pub_data >= timezone.now() - datetime.timedelta(days=1)


class Noticia(models.Model):
    titulo = models.CharField(max_length=50)
    texto = models.TextField()
    pub_data = models.DateTimeField('data de publicacao')
    imagem = models.ImageField(blank=True)

    def __str__(self):
        return self.titulo

    def __str__(self):
        return self.texto


class Comentario(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comentario_texto = models.CharField(max_length=200)
    gostos = models.IntegerField(default=0)
    pub_data = models.DateTimeField('data de publicacao')

    def __str__(self):
        return self.comentario_texto


class Subcomentario(models.Model):
    comentario = models.ForeignKey(Comentario, on_delete=models.CASCADE)
    subcomentario_texto = models.CharField(max_length=200)
    gostos = models.IntegerField(default=0)
    pub_data = models.DateTimeField('data de publicacao')

    def __str__(self):
        return self.subcomentario_texto

projeto/forum/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone

from .models import Post, Condutor, Comentario, Subcomentario, Noticia


def index(request):
    latest_post_list = Post.objects.order_by('-pub_data')[:10]
    context = {'latest_post_list': latest_post_list}
    return render(request, 'forum/index.html', context)


def detalhe(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'forum/detalhe.html', {'post': post})


@login_required(login_url='/forum/login')
def criarpost(request):
    if request.method == 'POST':
        try:
            post_titulo = request.POST.get("titulo")
            post_texto = request.POST.get("texto")
        except KeyError:
            return render(request, 'forum/criarpost.html')
        if post_titulo and post_texto:
            post = Post(post_titulo=post_titulo, post_texto=post_texto, pub_data=timezone.now())
            post.save()
            condutor = Condutor.objects.get(user=request.user)
            condutor.numero_posts += 1
            condutor.save()
            return HttpResponseRedirect(reverse('forum:detalhe', args=(post.id,)))
        else:
            return HttpResponseRedirect(reverse('forum:criarpost'))
    else:
        return render(request, 'forum/criarpost.html')


@login_required(login_url='/forum/login')
def criarcomentario(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        try:
            comentario_texto = request.POST.get("comentario")
        except KeyError:
            return render(request, 'forum/detalhe.html')
        if comentario_texto:
            comentario = Comentario(post=post, comentario_texto=comentario_texto, pub_data=timezone.now())
            comentario.save()
            return HttpResponseRedirect(reverse('forum:detalhe', args=(post.id,)))
        else:
            return HttpResponseRedirect(reverse('forum:detalhe', args=(post.id,)))
    else:
        return render(request, 'forum/detalhe.html',{'post': post})


@login_required(login_url='/forum/login')
def criarsubcomentario(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)
    if request.method == 'POST':
        try:
            subcomentario_texto = request.POST.get("subcomentario")
        except KeyError:
            return render(request, 'forum/detalhe.html')
        if subcomentario_texto:
            subcomentario = Subcomentario(comentario=comentario, subcomentario_texto=subcomentario_texto,
                                          pub_data=timezone.now())
            subcomentario.save()
            return HttpResponseRedirect(reverse('forum:detalhe', args=(comentario.post_id,)))
        else:
            return HttpResponseRedirect(reverse('forum:detalhe', args=(comentario.post_id,)))
    else:
        return render(request, 'forum/detalhe.html')


@login_required(login_url='/forum/login')
def gosto_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.gostos += 1
    post.save()
    return HttpResponseRedirect(reverse('forum:detalhe', args=(post_id,)))


@login_required(login_url='/forum/login')
@permission_required('forum.delete_post', login_url='/forum/login')
def removerpost(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return render(request, 'forum/removerpost.html')


@login_required(login_url='/forum/login')
@permission_required('forum.delete_comentario', login_url='/forum/login')
def removercomentario(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)
    comentario.delete()
    return HttpResponseRedirect(reverse('forum:detalhe', args=(comentario.post_id,)))


@login_required(login_url='/forum/login')
def gosto_comentario(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)
    comentario.gostos += 1
    comentario.save()
    return HttpResponseRedirect(reverse('forum:detalhe', args=(comentario.post_id,)))


def fazerLogin(request):
    if request.method == 'POST':
        user = request.POST.get("username")
        password = request.POST.get("password")
        a = authenticate(username=user, password=password)
        if a is not None:
            login(request, a)
            return HttpResponseRedirect(reverse('forum:index'))
        else:
            return render(request, 'forum/login_error.html')
    else:
        return render(request, 'forum/fazerLogin.html')


def signIn(request):
    username = request.POST.get("username")
    email = request.POST.get("email")
    password = request.POST.get("password")
    modelo_carro = request.POST.get("modelo_carro")
    nome = request.POST.get("nome")
    apelido = request.POST.get("apelido")
    if username and email and password and modelo_carro is not None:
        user = User.objects.create_user(username=username, email=email, password=password)
        user.first_name = nome
        user.last_name = apelido
        user.save()
        condutor = Condutor(user=user, modelo_carro=modelo_carro)
        condutor.save()
        return HttpResponseRedirect(reverse('forum:index'))
    else:
        return render(request, 'forum/signin.html', {'msg_erro': 'Preencher campos em falta.'})


def fazerLogout(request):
    logout(request)
    return render(request, 'forum/logout.html')


@login_required(login_url='/forum/login')
def info(request):
    return render(request, 'forum/info.html')


# Imagens
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage


def fazer_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        post = Post.objects.get(post_titulo=request.post.post_titulo)
        post.imagem = 'media/' + filename
        post.save()
        return render(request, 'forum/fazer_upload.html', {'uploaded_file_url': uploaded_file_url})
    return render(request, 'forum/fazer_upload.html')


def fazer_upload_avatar(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        condutor = Condutor.objects.get(user=request.user)
        condutor.avatar = 'media/' + filename
        condutor.save()
        return render(request, 'forum/fazer_upload_avatar.html', {'uploaded_file_url': uploaded_file_url})
    return render(request, 'forum/fazer_upload_avatar.html')


def index_noticia(request):
    latest_noticia_list = Noticia.objects.order_by('-pub_data')[:10]
    context = {'latest_noticia_list': latest_noticia_list}
    return render(request, 'forum/index_noticia.html', context)


@login_required(login_url='/forum/login')
def criarnoticia(request):
    if request.method == 'POST':
        try:
            titulo = request.POST.get("titulo")
            texto = request.POST.get("texto")
        except KeyError:
            return render(request, 'forum/criarnoticia.html')
        if titulo and texto:
            noticia = Noticia(titulo=titulo, texto=texto, pub_data=timezone.now())
            noticia.save()
            return HttpResponseRedirect(reverse('forum:index_noticia'))
        else:
            return HttpResponseRedirect(reverse('forum:criarnoticia'))
    else:
        return render(request, 'forum/criarnoticia.html')

projeto/forum/templates/forum/criarnoticia.html
<!DOCTYPE html>
<html lang="en">
{% extends "forum/index.html" %}
{% load static %}
{% block header %}
<header>
    <a href="http://127.0.0.1:8000/forum/">
        <img src="{% static 'forum/images/header1.jpg' %}" alt="CondutorForum" width="100%" height="auto">
    </a>
</header>
{% endblock %}

{% block sidebar %}
<aside>
    <div class="parent">
        {% if request.user.is_authenticated %}
        <div class="inline-block-child">
            <img class="foto_perfil" src="{% static user.condutor.avatar %}" alt="Foto de perfil"/>
        </div>
        <div class="inline-block-child">
            <a href="{% url 'forum:info' %}">
                <p>{{ request.user.username }}</p>
            </a>
            <a href="{% url 'forum:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'forum:fazerLogin' %}">Login</a>
            <a href="{% url 'forum:signin' %}">Criar conta</a>
            {% endif %}
        </div>
    </div>
</aside>
{% endblock %}

{% block conteudo %}
<h1>Crie uma notícia</h1>
<form method="post">
    {% csrf_token %}
    <p><label for="titulo">Título da notícia:</label>
        <input name="titulo" id="titulo" type="text"></p>
    <p><label for="texto">Texto da notícia:</label>
        <input name="texto" id="texto" type="text"></p>

    <button type="submit">Publicar</button>
    <button type="submit" formaction="{% url 'forum:index_noticia' %}">Voltar</button>
</form>
{% endblock %}
</html>

projeto/forum/templates/forum/criarpost.html
<!DOCTYPE html>
<html lang="en">
{% extends "forum/index.html" %}
{% load static %}
{% block header %}
<header>
    <a href="http://127.0.0.1:8000/forum/">
        <img src="{% static 'forum/images/header1.jpg' %}" alt="CondutorForum" width="100%" height="auto">
    </a>
</header>
{% endblock %}

{% block sidebar %}
<aside>
    <div class="parent">
        {% if request.user.is_authenticated %}
        <div class="inline-block-child">
            <img class="foto_perfil" src="{% static user.condutor.avatar %}" alt="Foto de perfil"/>
        </div>
        <div class="inline-block-child">
            <a href="{% url 'forum:info' %}">
                <p>{{ request.user.username }}</p>
            </a>
            <a href="{% url 'forum:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'forum:fazerLogin' %}">Login</a>
            <a href="{% url 'forum:signin' %}">Criar conta</a>
            {% endif %}
        </div>
    </div>
</aside>
{% endblock %}

{% block conteudo %}
<h1>Crie um post</h1>
<form method="post">
    {% csrf_token %}
    <p><label for="titulo">Título do novo post:</label>
        <input name="titulo" id="titulo" type="text"></p>
    <p><label for="texto">Texto do novo post:</label>
        <input name="texto" id="texto" type="text"></p>

    <button type="submit">Publicar</button>
    <button type="submit" formaction="{% url 'forum:index' %}">Voltar</button>
</form>
{% endblock %}
</html>

projeto/forum/templates/forum/detalhe.html
<!DOCTYPE html>
<html lang="pt">
{% extends "forum/index.html" %}
{% load static %}
{% block header %}
<header>
    <a href="http://127.0.0.1:8000/forum/">
        <img src="{% static 'forum/images/header1.jpg' %}" alt="CondutorForum" width="100%" height="auto">
    </a>
</header>
{% endblock %}

{% block sidebar %}
<aside>
    <div class="parent">
        {% if request.user.is_authenticated %}
        <div class="inline-block-child">
            <img class="foto_perfil" src="{% static user.condutor.avatar %}" alt="Foto de perfil"/>
        </div>
        <div class="inline-block-child">
            <a href="{% url 'forum:info' %}">
                <p>{{ request.user.username }}</p>
            </a>
            <a href="{% url 'forum:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'forum:fazerLogin' %}">Login</a>
            <a href="{% url 'forum:signin' %}">Criar conta</a>
            {% endif %}
        </div>
    </div>
</aside>
{% endblock %}

{% block conteudo %}
<h1>{{ post.post_titulo }} - {{ post.pub_data.date }}</h1>

{% if post.imagem.url is not None %}
<img src="{{ post.imagem.url }}"
     alt="{{ post.post_titulo }}"
     style="width: 30%"/>
{% endif %}
<p>{{ post.post_texto }}</p>
<form method="post">
    {% csrf_token %}
    <div>
        <button type="submit" formaction="{% url 'forum:gosto_post' post.id %}">👍 - {{ post.gostos }}</button>
        {% if request.user.is_superuser %}
        <button type="submit" formaction="{% url 'forum:removerpost' post.id %}">Remover post</button>
        {% endif %}
        <p><label for="comentario">Comentar:</label>
            <input name="comentario" id="comentario" type="text"></p>
        <button type="submit" formaction="{% url 'forum:criarcomentario' post.id %}">Postar comentário</button>
        <button class="voltar" type="submit" formaction="{% url 'forum:index' %}">Voltar</button>
    </div>

    <div class="caixinha">
        <ul>

            {% csrf_token %}
            {% for comentario in post.comentario_set.all %}
            <li>{{ comentario.comentario_texto }}
                <button type="submit" formaction="{% url 'forum:gosto_comentario' comentario.id %}">
                    👍 - {{ comentario.gostos }}
                </button>
                {% if request.user.is_superuser %}
                <button type="submit" formaction="{% url 'forum:removercomentario' comentario.id %}">
                    Remover comentario
                </button>
                {% endif %}

                <p><label for="subcomentario">Comentar:</label>
                    <input id="subcomentario" type="text" value="{{ val }}" name="subcomentario">{{ val }}</input>
                </p>

                <button type="submit" formaction="{% url 'forum:criarsubcomentario' comentario.id %}">
                    Postar sub comentário
                </button>


                <ul>
                    {% for subcomentario in comentario.subcomentario_set.all %}
                    <div class="caixinha_sub">
                        <li>
                            {{ subcomentario.subcomentario_texto }}
                        </li>
                    </div>
                    {% endfor %}
                </ul>

                {% endfor %}

            </li>
        </ul>
    </div>
</form>
{% endblock %}
</html>

projeto/forum/templates/forum/fazerLogin.html
<!DOCTYPE html>
<html lang="en">
{% extends "forum/index.html" %}
{% load static %}
{% block header %}
<header>
    <a href="http://127.0.0.1:8000/forum/">
        <img src="{% static 'forum/images/header1.jpg' %}" alt="CondutorForum" width="100%" height="auto">
    </a>
</header>
{% endblock %}

{% block sidebar %}
<aside>
    <div class="parent">
        {% if request.user.is_authenticated %}
        <div class="inline-block-child">
            <img class="foto_perfil" src="{% static user.condutor.avatar %}" alt="Foto de perfil"/>
        </div>
        <div class="inline-block-child">
            <a href="{% url 'forum:info' %}">
                <p>{{ request.user.username }}</p>
            </a>
            <a href="{% url 'forum:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'forum:fazerLogin' %}">Login</a>
            <a href="{% url 'forum:signin' %}">Criar conta</a>
            {% endif %}
        </div>
    </div>
</aside>
{% endblock %}

<body>
{% block conteudo %}
<h1>Fazer login</h1>
<form method="post">
    {% csrf_token %}
    <p><label for="username">Username:</label>
        <input name="username" id="username" type="text"></p>
    <p><label for="password">Password:</label>
        <input name="password" id="password" type="text"></p>

    <button type="submit" formaction="{% url 'forum:fazerLogin' %}">Fazer login</button>
    <button type="submit" formaction="{% url 'forum:index' %}">Voltar</button>
</form>
{% endblock %}
</body>
</html>

projeto/forum/templates/forum/fazer_upload_avatar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load static %}
<form method="post" enctype="multipart/form-data"
      action="{% url 'forum:fazer_upload_avatar' %}">
    {% csrf_token %}
    <input type="file" name="myfile">
    <input type="submit" value="Upload">
</form>

{% if uploaded_file_url %}
<p>Feito o upload para:
    <a href="{{ uploaded_file_url }}">
        {{ uploaded_file_url }}
    </a>
</p>
{% endif %}
<p>
    <a href="{% url 'forum:info' %}">
        <button type="submit">Voltar</button>
    </a>
</p>
</body>
</html>

projeto/forum/templates/forum/index.html
{% load static %}
<link rel="stylesheet" type="text/css"
      href="{% static 'forum/style.css' %}"/>

<!DOCTYPE html>
<html lang="pt">
{% block header %}
<header>
    <a href="http://127.0.0.1:8000/forum/">
        <img src="{% static 'forum/images/header1.jpg' %}" alt="CondutorForum" width="100%" height="auto">
    </a>
</header>
{% endblock %}

{% block sidebar %}
<aside>
    <div class="parent">
        {% if request.user.is_authenticated %}
        <div class="inline-block-child">
            <img class="foto_perfil" src="{% static user.condutor.avatar %}" alt="Foto de perfil"/>
        </div>
        <div class="inline-block-child">
            <a href="{% url 'forum:info' %}">
                <p>{{ request.user.username }}</p>
            </a>
            <a href="{% url 'forum:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'forum:fazerLogin' %}">Login</a>
            <a href="{% url 'forum:signin' %}">Criar conta</a>
            {% endif %}
        </div>
    </div>
</aside>
{% endblock %}

{% block conteudo %}
<div class="top">
    <a class="titulo"  href="{% url 'forum:index_noticia' %}">Notícias</a>
</div>
<div class="top">
    <a class="titulo" href="{% url 'forum:criarpost' %}">Criar post</a>
</div>


{% if latest_post_list %}
<ul>
    {% for post in latest_post_list %}
    <div class="caixinha">
        <li>
            <a class="titulo" href="{% url 'forum:detalhe' post.id %}">
                {{ post.post_titulo }} - {{ post.gostos }} 👍
            </a>
            <p>{{ post.post_texto }}</p>
        </li>
    </div>
    {% endfor %}
</ul>
{% else %}
<p>Nao há posts disponíveis.</p>
{% endif %}
{% endblock %}

</html>

projeto/forum/templates/forum/index_noticia.html
{% load static %}
<link rel="stylesheet" type="text/css"
      href="{% static 'forum/style.css' %}"/>

<!DOCTYPE html>
<html lang="pt">
{% block header %}
<header>
    <a href="http://127.0.0.1:8000/forum/index_noticia">
        <img src="{% static 'forum/images/header1.jpg' %}" alt="CondutorForum" width="100%" height="auto">
    </a>
</header>
{% endblock %}

{% block sidebar %}
<aside>
    <div class="parent">
        {% if request.user.is_authenticated %}
        <div class="inline-block-child">
            <img class="foto_perfil" src="{% static user.condutor.avatar %}" alt="Foto de perfil"/>
        </div>
        <div class="inline-block-child">
            <a href="{% url 'forum:info' %}">
                <p>{{ request.user.username }}</p>
            </a>
            <a href="{% url 'forum:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'forum:fazerLogin' %}">Login</a>
            <a href="{% url 'forum:signin' %}">Criar conta</a>
            {% endif %}
        </div>
    </div>
</aside>
{% endblock %}

{% block conteudo %}
<div class="top">
    <a class="titulo" href="{% url 'forum:index' %}">Posts</a>
</div>
{% if request.user.is_superuser %}
<div class="top">
    <a class="titulo" href="{% url 'forum:criarnoticia' %}">Criar notícia</a>
</div>
{% endif %}

{% if latest_noticia_list %}
<ul>
    {% for noticia in latest_noticia_list %}
    <div class="caixinha">
        <li>
            <p class="titulo">
                {{ noticia.titulo }}
            </p>
            <p>{{ noticia.texto }}</p>
        </li>
    </div>
    {% endfor %}
</ul>
{% else %}
<p>Nao há notícias.</p>
{% endif %}
{% endblock %}

</html>

projeto/forum/templates/forum/info.html
<!DOCTYPE html>
<html lang="en">
{% extends "forum/index.html" %}
{% load static %}
{% block header %}
<header>
    <a href="http://127.0.0.1:8000/forum/">
        <img src="{% static 'forum/images/header1.jpg' %}" alt="CondutorForum" width="100%" height="auto">
    </a>
</header>
{% endblock %}

{% block sidebar %}
<aside>
    <div class="parent">
        {% if request.user.is_authenticated %}
        <div class="inline-block-child">
            <img class="foto_perfil" src="{% static user.condutor.avatar %}" alt="Foto de perfil"/>
        </div>
        <div class="inline-block-child">
            <a href="{% url 'forum:info' %}">
                <p>{{ request.user.username }}</p>
            </a>
            <a href="{% url 'forum:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'forum:fazerLogin' %}">Login</a>
            <a href="{% url 'forum:signin' %}">Criar conta</a>
            {% endif %}
        </div>
    </div>
</aside>
{% endblock %}

<body>
{% block conteudo %}
<h1>Informação do utilizador</h1>
<ul>
    <p><img class="foto_perfil_info" src="{% static user.condutor.avatar %}" alt="Foto de perfil"/></p>
    <li><p>Nome: {{ request.user.first_name }} {{ request.user.last_name }}</p></li>
    <li><p>Username: {{ request.user.username }}</p></li>
    <li><p>Número de posts: {{ request.user.condutor.numero_posts }}</p></li>
    <li><p>Email: {{ request.user.email }}</p></li>
    <li><p>Modelo do carro: {{ request.user.condutor.modelo_carro }}</p></li>
    <li><a href="{% url 'forum:fazer_upload_avatar' %}"><button type="submit">Alterar foto</button></a></li>


</ul>
<a href="{% url 'forum:index' %}">
    <button type="submit">Voltar</button>
</a>
{% endblock %}
</body>
</html>

projeto/forum/templates/forum/login_error.html
<!DOCTYPE html>
<html lang="en">
{% extends "forum/index.html" %}
{% load static %}
{% block header %}
<header>
    <a href="http://127.0.0.1:8000/forum/">
        <img src="{% static 'forum/images/header1.jpg' %}" alt="CondutorForum" width="100%" height="auto">
    </a>
</header>
{% endblock %}

{% block sidebar %}
<aside>
    <div class="parent">
        {% if request.user.is_authenticated %}
        <div class="inline-block-child">
            <img class="foto_perfil" src="{% static user.condutor.avatar %}" alt="Foto de perfil"/>
        </div>
        <div class="inline-block-child">
            <a href="{% url 'forum:info' %}">
                <p>{{ request.user.username }}</p>
            </a>
            <a href="{% url 'forum:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'forum:fazerLogin' %}">Login</a>
            <a href="{% url 'forum:signin' %}">Criar conta</a>
            {% endif %}
        </div>
    </div>
</aside>
{% endblock %}

<body>
{% block conteudo %}
<h1>Erro no login!</h1>
<form method="post">
    {% csrf_token %}
    <button type="submit" formaction="{% url 'forum:index' %}">Voltar</button>
</form>
{% endblock %}
</body>
</html>

projeto/forum/templates/forum/logout.html
<!DOCTYPE html>
<html lang="en">
{% extends "forum/index.html" %}
{% load static %}
{% block header %}
<header>
    <a href="http://127.0.0.1:8000/forum/">
        <img src="{% static 'forum/images/header1.jpg' %}" alt="CondutorForum" width="100%" height="auto">
    </a>
</header>
{% endblock %}

{% block sidebar %}
<aside>
    <div class="parent">
        {% if request.user.is_authenticated %}
        <div class="inline-block-child">
            <img class="foto_perfil" src="{% static user.condutor.avatar %}" alt="Foto de perfil"/>
        </div>
        <div class="inline-block-child">
            <a href="{% url 'forum:info' %}">
                <p>{{ request.user.username }}</p>
            </a>
            <a href="{% url 'forum:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'forum:fazerLogin' %}">Login</a>
            <a href="{% url 'forum:signin' %}">Criar conta</a>
            {% endif %}
        </div>
    </div>
</aside>
{% endblock %}

<body>
{% block conteudo %}
<h1>Logout efetuado</h1>
<form method="post">
    {% csrf_token %}
    <button type="submit" formaction="{% url 'forum:index' %}">Voltar</button>
</form>
{% endblock %}
</body>
</html>

projeto/forum/templates/forum/removercomentario.html
<!DOCTYPE html>
<html lang="en">
<body>
<form action="{% url 'forum:index' %}" method="post">
    {% csrf_token %}
    <p>Comentario removido</p>
    <button type="submit" formaction="{% url 'forum:index' %}">Voltar</button>
</form>
</body>
</html>